services:
  backend-java:
    image: ghcr.io/renatoxico/javapi:latest
    container_name: backend-java
    ports:
      - "9090:9090"
    env_file:
      - .env
    restart: always
    depends_on:
      - backend-python
    networks:
      - app-network

  backend-python:
    image: ghcr.io/renatoxico/py-extractor:latest
    container_name: backend-python
    ports:
      - "9000:9000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
