services:
  backend-java:
    build:
      context: ./javapi # Path to the directory containing the Dockerfile for backend-java
    container_name: backend-java
    ports:
      - "9090:9090"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
