version: '3.8'
services:
  backend-java:
    image: ghcr.io/renatoxico/javapi:latest
    container_name: backend-java
    ports:
      - "9090:9090"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - app-network

  frontend:
    image: ghcr.io/renatoxico/svelte-frontend:latest
    container_name: extractapi_frontend_prod
    ports:
      - "3000:80"
    depends_on:
      - backend-java
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge