spring.application.name=API
server.port=9090
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=2MB

spring.datasource.url=jdbc:postgresql://localhost:5432/extract_process
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
