name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: TOXIC SERVER
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and tag images
        run: |
          docker compose build --no-cache
          docker tag extractapi-backend-java ghcr.io/renatoxico/javapi:latest
          docker tag extractapi-backend-python ghcr.io/renatoxico/py-extractor:latest

      - name: Push images to GHCR
        run: |
          docker push ghcr.io/renatoxico/javapi:latest
          docker push ghcr.io/renatoxico/py-extractor:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: TOXIC SERVER
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/ubuntu/ExtractAPI
            echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans