name: Deploy to VPS

on:
  push:
    branches: [ "master" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push images
        run: |
          docker compose build
          docker compose push

  deploy:
    runs-on: ubuntu-latest
    environment: TOXIC SERVER 
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /app/ExtractAPI
            git pull
            docker compose pull
            docker compose up -d --remove-orphans