name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: TOXIC SERVER
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build backend image
        run: |
          docker compose build --no-cache backend-java
          docker tag extractapi-backend-java ghcr.io/${{ github.repository_owner }}/javapi:latest

      - name: Push backend image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/javapi:latest

      - name: Build and push frontend image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/svelte-frontend:latest ./svelte-frontend
          docker push ghcr.io/${{ github.repository_owner }}/svelte-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: TOXIC SERVER
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/extractor/ExtractAPI
            echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/javapi:latest
            docker pull ghcr.io/${{ github.repository_owner }}/svelte-frontend:latest
            docker compose pull
            docker compose up -d --remove-orphans
